[package]
name = "rsplayer_config"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true
sled.workspace = true
api_models = { path = "../rsplayer_api_models"}
