[package]
name = "api_models"
version = "0.2.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true

validator = { version = "0.16.0", features = ["derive"] }
regex = "1"
uuid = { version = "1", features = ["serde", "v4"] }
strum = "0.24.1"
strum_macros = "0.24.3"
num-traits = { version = "0.2.15", default-features = false }
num-derive = { version = "0.3.3", default-features = false }
# md5 = "0.7.0"