[workspace]
members = [
    "rsplayer_api_models",
    "rsplayer_backend",
    "rsplayer_metadata",
    "rsplayer_config",
    "rsplayer_playback",
    # "rsplayer_web_ui"
]
exclude = ["rsplayer_web_ui"]
