[package]
name = "dplay"
version = "0.2.0"
authors = ["Dragan Ljubojevic <dragan.ljubojevic@gmail.com>"]
edition = "2021"

[features]
hw_gpio =  ["gpio-cdev","rpi_embedded","linux-embedded-hal", "embedded-hal"]

hw_oled = ["hw_gpio", "embedded-graphics"]
hw_dac = ["hw_gpio"]
hw_ir_control = []


backend_mpd = ["mpd"]
backend_lms = []


default = ["backend_mpd"]

[dependencies]
api_models = { path = "dplayer-api-models" }

#logging
log = "0.4"
env_logger = "0.8.3"
cfg-if = "1.0.0"

#warp
tokio = { version = "1.17.0", features = ["full"] }
warp = "0.3.2"
futures = { version = "0.3.21", default-features = false }
tokio-stream = "0.1.8"

#json serde
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

#mpd
mpd = { version = "0.0.12", optional = true }

#other
failure = "0.1.7"
unidecode = "0.3.0"
alsa = "0.6.0"
url = "2.2.0"
num-traits = { version = "0.2.12", default-features = false }
num-derive = { version = "0.3.2", default-features = false }
pickledb = "0.4.1"
log4rs = "1.0.0"

#gpio, i2c
gpio-cdev = {optional = true, version="0.4"}
rpi_embedded = {optional = true, version="0.1.0"}
linux-embedded-hal = {optional = true, version="0.3.0"}
embedded-hal = {optional = true, version="0.2.4"}

#oled
embedded-graphics = {optional=true, version = "0.7.1" }
# st7920 = { optional = true, version = "0.2.2" }

# spotify
[dependencies.rspotify]
version = "0.11.5"
features = ["client-ureq", "ureq-rustls-tls"]
default-features = false

[profile.release]
opt-level = 3
# debug = false
# debug-assertions = false
# codegen-units = 1
# strip = true