[workspace]
resolver = "2"
members = [
    "rsplayer_api_models",
    "rsplayer_backend",
    "rsplayer_metadata",
    "rsplayer_config",
    "rsplayer_playback",
    "rsplayer_hardware",
#    "rsplayer_web_ui"
]
exclude = ["rsplayer_web_ui"]

[workspace.dependencies]
log = { version = "0.4.21" }
env_logger = "0.11.3"
anyhow = "1.0.80"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
sled = "0.34.7"
symphonia = { version = "0.5.4", features = ["all"] }
cfg-if = "1.0.0"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
futures = { version = "0.3.30", default-features = false }
tokio-stream = "0.1.14"
chrono = {verson = "0.4.31",  features = ["serde"]}
uuid = { version = "1.7.0", features = ["serde", "v4"] }