[workspace]
members = [
    "rsplayer_api_models",
    "rsplayer_backend",
    "rsplayer_metadata",
    "rsplayer_config",
    "rsplayer_playback",
    "rsplayer_hardware",
    # "rsplayer_web_ui"
]
exclude = ["rsplayer_web_ui"]

[workspace.dependencies]
log = { version = "0.4" }
env_logger = "0.10.0"
anyhow = "1.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"

cfg-if = "1.0.0"
tokio = { version = "1", features = ["full", "tracing"] }
futures = { version = "0.3.24", default-features = false }
tokio-stream = "0.1.10"

