[target.armv7-unknown-linux-gnueabihf]
image = "ljufa/rsplayer-cross-armv7:latest"

[target.aarch64-unknown-linux-gnu]
image = "ljufa/rsplayer-cross-aarch64:latest"
linker = "clang"
rustflags = ["-C","link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-unknown-linux-gnu]
image = "ljufa/rsplayer-cross-x86_64:latest"
