[target.armv7-unknown-linux-gnueabihf]
image = "ljufa/rsplayer-cross-armv7:latest"

[target.aarch64-unknown-linux-gnu]
image = "ljufa/rsplayer-cross-aarch64:latest"
linker = "clang"
rustflags = ["-C","link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends wget libssl-dev libasound-dev libasound2-dev"]
