[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install --assume-yes --no-install-recommends libssl-dev:armhf libasound-dev:armhf",
    "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=1"
]
[target.arm-unknown-linux-gnueabihf]
image = "ljufa/rsplayer_cross_armhf:0.0.1"

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes --no-install-recommends wget libssl-dev:arm64 libasound-dev:arm64 libasound2-dev:arm64",
    "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=1",
]

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install --assume-yes --no-install-recommends wget libssl-dev libasound-dev libasound2-dev"]
