version: "3"
services:
  rsplayer:
    image: ljufa/rsplayer:latest
    devices:
      - /dev/snd
    ports:
      - 8000:80
    environment:
      - PORT=80
      - TLS_PORT=443
      - TLS_CERT_PATH=/self.crt
      - TLS_CERT_KEY_PATH=/self.key
    volumes:
      - ${MUSIC_DIR}:/music:ro
      - 'rsplayer_volume:/opt/rsplayer'
    restart: unless-stopped

volumes:
  rsplayer_volume:
    driver: local
