[env]
RPI_HOST = "192.168.5.60" 
TARGET = "aarch64-unknown-linux-gnu"
RELEASE_VERSION = "0.2.2"

[config]
default_to_workspace = false


# ---- BUILD Backend----
[tasks.build_release]
install_crate = { crate_name = "cross", binary = "cross", test_arg = "-V", force = false }
command = "cross"
args = [
    "build",
    "--target",
    "${TARGET}",
    "--release",
    "--package",
    "rsplayer",
    "--bin",
    "rsplayer",
]
[tasks.build_ui_release]
cwd = "rsplayer_web_ui"
command = "cargo"
args = ["make", "build_release"]

[tasks.package_deb_release]
install_crate = { crate_name = "cargo-deb", binary = "deb", test_arg = "--version", force = false }
command = "cargo"
args = [
    "deb",
    "--no-build",
    "-p",
    "rsplayer",
    "--target=${TARGET}",
    "--deb-version",
    "${RELEASE_VERSION}",
]

[tasks.librespot_build_release]
cwd = "/tmp"
script = [
    "rm -rf librespot",
    "git clone https://github.com/librespot-org/librespot.git",
    "cd librespot",
    "git checkout master",
    "cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/Cross.toml .",
    "cross build --target aarch64-unknown-linux-gnu --release --no-default-features --features alsa-backend",
    "cp -f target/aarch64-unknown-linux-gnu/release/librespot ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/PKGS/debian-arm64/usr/local/bin",
]

# ---- LINT ----
[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = [
    "clippy",
    "--fix",
    "--allow-dirty",
    "--all-features",
    "--",
    "--deny", "warnings",
    "--deny", "clippy::pedantic",
    "--deny", "clippy::nursery",
    "--allow","clippy::use_self",
    "--allow","clippy::module_name_repetitions",
    "--allow","clippy::must_use_candidate",
    "--allow","clippy::let_underscore_drop"
]

[tasks.format]
description = "Format with rustfmt"
command = "cargo"
args = ["fmt"]


# ---- Local DEV ----
[tasks.run_local]
env = { "RUST_LOG"="rsplayer=debug,warp=debug", "RUST_BACKTRACE"="full", "RSPLAYER_HTTP_PORT"="8000"}
command = "cargo"
args = ["run"]


[tasks.copy_remote]
dependencies = ["build_release"]
script = [
    "rsync -avvP --rsync-path=\"sudo rsync\" target/${TARGET}/release/rsplayer pi@${RPI_HOST}:/usr/local/bin",
]

[tasks.package_deb_local]
dependencies = ["build_ui_release", "build_release", "package_deb_release"]


[tasks.librespot_build_local]
cwd = "/tmp"
script = [
    "rm -rf librespot",
    "git clone https://github.com/librespot-org/librespot.git",
    "cd librespot",
    "git checkout master",
    "cargo build --release --no-default-features --features alsa-backend",
    "cp -f target/release/librespot ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/.run",
    "rm -rf librespot",
]
