[package]
name = "rsplayer_web_ui"
version = "0.1.0"
authors = ["dragan <dragan.ljubojevic@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.9.2"
serde = "1.0.144"
uuid = { version = "1.1.2"}
indexmap = { version = "1.9.1", features = ["serde-1"] }
enclose = "1.1.8"
strum = "0.24.1"
strum_macros = "0.24.3"
api_models = { path = "../rsplayer_api_models" }


[features]
remote = []
local = []
default = ["remote"]
