[package]
name = "rsplayer_web_ui"
version = "0.1.0"
authors = ["dragan <dragan.ljubojevic@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = { version = "0.10.0", features = ["routing"] }
serde = "1"
serde_json = "1"
uuid = { version = "1.6.1" }
indexmap = { version = "2.1.0", features = ["serde"] }
enclose = "1.1.8"
strum = "0.25.0"
strum_macros = "0.25.2"
api_models = { path = "../rsplayer_api_models" }
wasm-sockets = { version = "1" }
gloo-console = { version = "0.3.0" }
gloo-net = { version = "0.5.0" }
indextree = "4.6.0"


[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[features]
remote = []
local = []
default = ["remote"]

[profile.release]
lto = true
opt-level = "s"
