# ---- BUILD UI----
[tasks.build_release]
# install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", force = false }
command = "wasm-pack"
args = [
    "build",
    "--target",
    "web",
    "--out-name",
    "package",
    "--out-dir",
    "public/pkg",
]

[tasks.build_dev]
description = "Build with wasm-pack"
# install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", force = false }
command = "wasm-pack"
args = [
    "build",
    "--target",
    "web",
    "--out-name",
    "package",
    "--dev",
    "--out-dir",
    "public/pkg",
]
