[package]
name = "rsplayer_playback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
api_models = { path = "../rsplayer_api_models" }
rsplayer_metadata = { path = "../rsplayer_metadata" }
rsplayer_config = { path = "../rsplayer_config" }

# general
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
#mpd
mpd = { version = "0.0.12" }

# symphonia
symphonia = { version = "0.5.1", features = ["all"] }
cpal = "0.15.0"
rb = "0.4.1"
rubato = "0.12.0"
ureq = "2.6.2"

#spotify
rspotify = { version = "0.11.6", features = [
    "client-ureq",
    "ureq-rustls-tls",
], default-features = false }

mockall_double = "0.3.0"

[dev-dependencies]
mockall = "0.11.0"
random-string = "1.0.0"
