[package]
name = "rsplayer_playback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
api_models = { path = "../rsplayer_api_models" }
rsplayer_metadata = { path = "../rsplayer_metadata" }
rsplayer_config = { path = "../rsplayer_config" }
# general
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
symphonia.workspace = true
tokio.workspace = true

# symphonia
cpal = "0.15.2"
rb = "0.4.1"
# rubato = "0.12.0"
ureq = "2.9.1"


mockall_double = "0.3.0"

[dev-dependencies]
mockall = "0.11.4"
random-string = "1.0.0"
