[package]
name = "rsplayer_playback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
api_models = { path = "../rsplayer_api_models" }
rsplayer_metadata = { path = "../rsplayer_metadata" }
rsplayer_config = { path = "../rsplayer_config" }

# general
anyhow = "1.0"
log = { version = "0.4" }
env_logger = "0.10.0"
#mpd
mpd = { version = "0.0.12" }

# symphonia
symphonia = { version = "0.5.1", features = [
    "aac",
    "alac",
    "mp3",
    "isomp4",
    "flac",
    "wav",
    "ogg",
    "vorbis",
    "pcm",
] }
cpal = { path = "/home/dlj/github/cpal" }
rb = "0.3.2"

#spotify
rspotify = { git = "https://github.com/ljufa/rspotify.git", branch = "add_user_queue_ep", features = [
    "client-ureq",
    "ureq-rustls-tls",
], default-features = false }

# sled 
sled = "0.34.7"

mockall_double = "0.3.0"

[dev-dependencies]
mockall = "0.11.0"
random-string = "1.0.0"
