name: Release from tag
on:
  push:
    tags:
      - "*.*.*"
env:
  CARGO_TERM_COLOR: always

jobs:
      
  build_ui:
    name: Build UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: davidB/rust-cargo-make@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack
    - name: Build release
      run: cargo make build_ui_release
    - name: Upload pkg dir
      uses: actions/upload-artifact@v3
      with:
        name: web_ui
        path: target/ui
    
  build_backend:
    needs: build_ui
    strategy:
      matrix:
        target: ["armv7-unknown-linux-gnueabihf","aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: davidB/rust-cargo-make@v1
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall
    - name: Install tools
      run: cargo make install_tools
    - name: Download web_ui
      uses: actions/download-artifact@v3
      with:
        name: web_ui
        path: target/ui
    # - name: Display structure of downloaded files
    #   run: ls -R target
    - name: Build Backend
      run: cargo make --env TARGET=${{ matrix.target }} build_release
    - name: Create deb package
      run: cargo make --env RELEASE_VERSION=${GITHUB_REF_NAME} --env TARGET=${{ matrix.target }} package_deb_release
    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: deb-${{ matrix.target }}
        path: target/${{ matrix.target }}/debian/*.deb
  publish:
    needs: build_backend
    name: Release deb packages
    runs-on: ubuntu-latest
    steps:
    - name: Download deb packages
      uses: actions/download-artifact@v3
    # - name: Display structure of downloaded files
    #   run: ls -R
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        prerelease: true
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          **/*.deb
          