name: Release from tag
on:
  push:
    tags:
      - "v*.*.*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - uses: davidB/rust-cargo-make@v1
    - uses: jetli/wasm-pack-action@v0.3.0
    - name: Build UI
      run: cargo make ui_release_build
    - name: Build Backend 
      run: cargo make backend_build_release
    - name: Create deb
      run: cargo make --env RELEASE_VERSION=${GITHUB_REF_NAME} package_deb
    - name: Release deb file
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/debian/*.deb
          
