name: Build and test
on:
  push:
    branches:
      - "main"
env:
  CARGO_TERM_COLOR: always

jobs:
    
  build_backend:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - uses: davidB/rust-cargo-make@v1
    - uses: taiki-e/install-action@v1
      with:
        tool: cross
    - name: Clippy lint
      run: cross make clippy --target aarch64-unknown-linux-gnu
    - name: Run tests
      run: cross test --target aarch64-unknown-linux-gnu
  